name: AbrPlus-Ui-Kit

trigger:
  batch: true
  branches:
    include:
      - develop

pool:
  name: Dev Agents

steps:
  # 1️⃣ Checkout repo
  - checkout: self
    clean: true
    persistCredentials: true # required for semantic-release git tags

  # 2️⃣ Install Node.js
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "22.x"
      checkLatest: true

  # 3️⃣ Install pnpm
  - script: npm i -g pnpm@8.14.0
    displayName: "Install pnpm"

  # 4️⃣ Install dependencies
  - script: pnpm install --frozen-lockfile
    displayName: "Install dependencies"

  # 5️⃣ Build UI Kit
  - script: pnpm vite build
    displayName: "Build UI Kit"
    env:
      NODE_OPTIONS: --max_old_space_size=4096

  # 6️⃣ Release + publish to npm
  - script: pnpm semantic-release
    displayName: "Release & publish to npm"
    env:
      NPM_TOKEN: $(PUBLISH_TOKEN)
