name: AbrPlus-Ui-Kit

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Dev Agents

steps:
  # Checkout repo
  - checkout: self
    clean: true
    persistCredentials: true # required for semantic-release git tags
    fetchDepth: 0 # ensures full history for tagging

  # Install Node.js
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "22.x"
      checkLatest: true

  # Install pnpm
  - script: npm i -g pnpm@8.14.0
    displayName: "Install pnpm"

  # Install dependencies
  - script: pnpm install --frozen-lockfile
    displayName: "Install dependencies"

  # Build UI Kit
  - script: pnpm vite build
    displayName: "Build UI Kit"
    env:
      NODE_OPTIONS: --max_old_space_size=4096

  - script: git fetch origin develop && git reset --hard origin/develop
    displayName: "Sync local branch with remote"

  # Release + publish to npm
  - script: git pull origin develop && pnpm release
    displayName: "Bump version & Publish UI Kit"
    env:
      PUBLISH_TOKEN: $(PUBLISH_TOKEN)
      GIT_AUTH_TOKEN: $(GIT_PAT)
