name: AbrPlus-Ui-Kit

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Dev Agents

steps:
  - checkout: self
    clean: true
    persistCredentials: true
    fetchDepth: 0

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "22.x"
      checkLatest: true

  - script: npm i -g pnpm@8.14.0
    displayName: "Install pnpm"

  - script: pnpm install --frozen-lockfile
    displayName: "Install dependencies"

  - script: pnpm vite build
    displayName: "Build UI Kit"
    env:
      NODE_OPTIONS: --max_old_space_size=4096

  - powershell: |
      "//registry.npmjs.org/:_authToken=$env:NPM_TOKEN" |
      Out-File "$env:USERPROFILE\.npmrc" -Encoding ascii -Force
    displayName: "Configure npm authentication"
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  # Run semantic-release (no npm publish)
  - script: pnpm release
    displayName: "Generate changelog & git push"
    env:
      GIT_AUTH_TOKEN: $(GIT_PAT)

  # Manual npm publish
  - script: pnpm publish --access public --no-git-checks
    displayName: "Publish to npm"
    env:
      NPM_TOKEN: $(NPM_TOKEN)
