name: AbrPlus-Ui-Kit

trigger:
  batch: true
  branches:
    include:
      - develop

pool:
  name: Dev Agents

steps:
  # Checkout repo (needed for semantic-release tags)
  - checkout: self
    clean: true
    persistCredentials: true
    fetchDepth: 0

  # Install Node.js
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "22.x"
      checkLatest: true

  # Install pnpm
  - script: npm i -g pnpm@8.14.0
    displayName: "Install pnpm"

  # Install dependencies
  - script: pnpm install --frozen-lockfile
    displayName: "Install dependencies"

  # Build UI Kit
  - script: pnpm vite build
    displayName: "Build UI Kit"
    env:
      NODE_OPTIONS: --max_old_space_size=4096

  # Configure npm auth (CI-safe, Windows-safe)
  - powershell: |
      $npmrc = "$env:USERPROFILE\.npmrc"
      "//registry.npmjs.org/:_authToken=$env:NPM_TOKEN" | Out-File -FilePath $npmrc -Encoding ascii -Force
    displayName: "Configure npm authentication"
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  # Release
  - script: pnpm release
    displayName: "Bump version & Publish UI Kit"
    env:
      NPM_TOKEN: $(NPM_TOKEN)
      GIT_AUTH_TOKEN: $(GIT_PAT)
