name: Storybook

trigger:
  batch: true
  branches:
    include:
      - develop

pool:
  name: Dev Agents

steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
      checkLatest: true
    enabled: false
    displayName: "Install Node.js"

  - script: |
      npm i -g pnpm@8.14.0
    enabled: false
    displayName: "Install Package Manager"

  - script: |
      pnpm install
    enabled: false
    displayName: "Install Dependencies"

  - script: |
      pnpm storybook:build
    displayName: "Build StoryBook"
    env:
      NODE_OPTIONS: --max_old_space_size=4096

  - task: CopyFiles@2
    displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)/storybook-static"
      Contents: |
        **/*
      TargetFolder: "$(Build.ArtifactStagingDirectory)/archive/storybook"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/archive/storybook"
    condition: succeededOrFailed()
